### ISSUE TITLE
Machine Learning ToDo

### ISSUE THREAD

**Issue by Afats** [Afats/heartbeat-authentication#3]
- [x] Label columns/rows of data for ML
- [x] Linear SVM with default parameters using sklearn for training and prediction
- [ ] Only use level 2-4 from feature extraction
- [ ] Training and testing of ML algorithm
- [ ] Program Terminal UI for demo (assumes model is already trained):
    - Python program in loop:
        - [ ] 1. Option to authenticate user
            - [ ] Asks user to collect 1-5 heartbeat samples (displays samples collected on terminal)
            - [ ] calls receiver.py, then adds data collected to a csv in the proper format.
            - [ ] CSV is then used in: 
                - 1. segmentation
                - 2. Feature extraction
                - 3. ML prediction 
            - [ ] Prediction result is displayed on terminal (if user is authenticated or not)
- [ ] 5-fold cross validation to estimate accuracy of ML model
- [ ] Data pipelining (needed for the demo)
